# Generated by Django 4.2 on 2023-06-03 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_member_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.organization'),
        ),
    ]
